name: ubuntu

on: [push, pull_request]

jobs:
  build:
  
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-22.04] #, ubuntu-20.04]
        build_type: ["Debug"] #, "Release"]
        generator: ["Ninja"] #, "Unix Makefiles"]

    env:
      CC: gcc-10
      CXX: g++-10
      BUILD_DIR: ${{github.workspace}}/build/${{matrix.build_type}}

    steps:
    - uses: actions/checkout@v3

    - name: Install Ninja
      run: |
        sudo apt-get update
        sudo apt-get install xorg
        sudo apt-get install ninja-build
        
    - name: Install Conan
      run: |
        pip install conan
        conan profile new default --detect 
        conan profile update settings.compiler=gcc default
        conan profile update settings.compiler.version=10 default
        conan profile update settings.compiler.libcxx=libstdc++11 default
    
        export CONAN_SYSREQUIRES_SUDO=0
        export CONAN_SYSREQUIRES_MODE=enabled
        export DEBIAN_FRONTEND=noninteractive
        
        conan install . \
          -c tools.system.package_manager:mode=install \
          --install-folder ${{env.BUILD_DIR}}/modules \
          --settings build_type=${{matrix.build_type}}\
          --settings compiler=gcc \
          --settings compiler.version=10 \
          --build missing \
          --update
        
    - name: Configure
      run: |
        echo Configure
        cmake -S . -B ${{env.BUILD_DIR}} -G ${{matrix.generator}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DVIDEO_IO_BUILD_TESTS=OFF
    
    - name: Build
      run: |
        echo Build
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        echo Test
        ctest --test-dir ./build/${BUILD_TYPE} --config ${BUILD_TYPE} --output-junit results.xml --output-on-failure -j$(nproc)
